name: Feature flags workflow trigger

on:
 
  pull_request:
    branches: ["main"]
    types: [opened, closed]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR event
        run: |
          if [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
            if [ "${GITHUB_EVENT_ACTION}" == "opened" ]; then
              echo "PR opened"
            elif [ "${GITHUB_EVENT_ACTION}" == "closed" ]; then
              echo "PR closed"
            fi
          fi
